# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      cd src/BizBio.UI
      npm install
    displayName: 'Install Dependencies'

  - script: |
      cd src/BizBio.UI
      npm run build
    displayName: 'Build Nuxt Application'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: 'src/BizBio.UI/.output'
      ArtifactName: 'ui-build'
